name: Scheduled Cron Jobs

on:
  schedule:
    # Run overdue stock check daily at 9 AM Thailand time (2 AM UTC)
    - cron: "0 2 * * *"
    # Run tax deadline check daily at 10 AM Thailand time (3 AM UTC)
    - cron: "0 3 * * *"
  # Allow manual triggers
  workflow_dispatch:

jobs:
  notify-overdue-stock:
    runs-on: ubuntu-latest
    steps:
      - name: Call overdue stock API
        run: |
          curl -X POST ${{ secrets.VERCEL_DEPLOYMENT_URL }}/api/notify-overdue-stock \
            -H "Authorization: Bearer ${{ secrets.API_SECRET }}" \
            -H "Content-Type: application/json" \
            -w "HTTP Status: %{http_code}\n"

  notify-tax-deadline:
    runs-on: ubuntu-latest
    steps:
      - name: Call tax deadline API
        run: |
          curl -X POST ${{ secrets.VERCEL_DEPLOYMENT_URL }}/api/notify-tax-deadline \
            -H "Authorization: Bearer ${{ secrets.API_SECRET }}" \
            -H "Content-Type: application/json" \
            -w "HTTP Status: %{http_code}\n"
